dist: bionic
language: php

git:
  submodules: true

php:
  - 7.2

before_install:
  - travis_retry composer self-update
  - composer config discard-changes true

before_script:
  - composer install --prefer-dist --no-interaction
  - composer run prepare

script:
  - vendor/bin/phpunit -c phpunit.xml --testdox --verbose

matrix:
  fast_finish: true
